### ISSUE TITLE
Question about User

### ISSUE THREAD

**Issue by RaymondSchnyder** [mezz64/pyEmby#4]
Is it possible to add/edit Users with this API Wrapper? Or have i to do the methods for this myself?
Could you lead me in the right direction?

Thank you :)

**Comment by mezz64** [comment]
This library is primarily for reading media status from Emby.  It does not provide any functionality to add/edit data, including users.  

Your best option is to make a fork and add in the functionality you need.  If you get everything working well i'd be happy to accept a PR with your changes.
