### ISSUE TITLE
Support Jellyfin?

### ISSUE THREAD

**Issue by bfayers** [mezz64/pyEmby#6]
Would it be possible for this client to be able to support the [Jellyfin](https://github.com/jellyfin) project as the fully open source fork it would be nice to continue to use a pre-existing opensource python library.

**Comment by mezz64** [comment]
Could you let me know what doesn't work?  The Emby API hasn't changed in some time so if Jellyfin is based on Emby 3.5.2 I'd think it should more or less work as-is.

**Comment by JustAMan** [comment]
This is probably a future-proofing question, given Emby released 4.0 recently and it's likely their and our API will diverge over time.

**Comment by mezz64** [comment]
In general, I'm open to accommodating Jellyfin.  I'd be willing to fix any issues preventing present compatibility and would asses any future divergence when it happens, either by adding the appropriate options or making a fork.

**Comment by JustAMan** [comment]
Great, thanks!

**Comment by olskar** [comment]
I get this in Home Assistant using pyemby in jellyfin @mezz64 

`2020-01-18 19:37:59 ERROR (MainThread) [pyemby.server] Error fetching Emby data: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='http://localhost:8096/jellyfin/web/index.html
2020-01-18 19:37:59 ERROR (MainThread) [pyemby.server] Unable to register emby client.`

**Comment by mezz64** [comment]
Can you post the full log please?  What are you supplying as the host path?

**Comment by mezz64** [comment]
Second followup, have you read the Jellyfin release notes from 10.4.1 (https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1)?  Given the path posted in your error text it looks like this may be your problem.  Please double check your host path.

**Comment by olskar** [comment]
Hello @mezz64 !

That is everything related to pyemby in my HomeAssistant log.

I tried both localhost and my ip-adress with the same result.

**Comment by olskar** [comment]
This is on nightly 2020-02-24 btw.

Do you mean url should be `http://localhost:8096/jellyfin/web/index.html#!/home.html` instead of `http://localhost:8096/jellyfin/web/index.html` ?

**Comment by mezz64** [comment]
Follow the instructions in those release notes to determine your BASE_PATH.  That will determine whether or not you need to specify `/jellyfin` after the host path.  Post your yaml for how you have the component configured.  Others are using this without issue so I think it's likely a configuration error since Jellyfin has not diverged from the Emby API specifications.

**Comment by anthonylavado** [comment]
Thanks @mezz64 :-)
Let us know if you need any help. Eventually it may diverge, but we'll hope to give notice before that happens. At that point I may ask for advice on getting included in Home Assistant 👍

**Comment by olskar** [comment]
Thanks @mezz64 I removed jellyfin from baseurl in jellyfin settings, works now.

I
