### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rynr** [mezz64/pyEmby#7]
Within [home-assistant](https://github.com/home-assistant/core), the current status of a [jellyfin](https://github.com/jellyfin/jellyfin) instance is not updated. The logs show the following:

```
ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyemby/server.py", line 287, in socket_connection
    self.process_msg(msg.data)
  File "/usr/local/lib/python3.8/site-packages/pyemby/server.py", line 319, in process_msg
    self.update_device_list(self._sessions)
  File "/usr/local/lib/python3.8/site-packages/pyemby/server.py", line 342, in update_device_list
    dev_name, device['NowPlayingItem']['Type'],
TypeError: 'NoneType' object is not subscriptable
```

This looks to me like an issue in pyemby, perhaps just some mapping, or is this an issue by [jellyfin](https://github.com/jellyfin/jellyfin) not implementing the API correclty?

This has been reported in home-assistant/core#38501

**Comment by rynr** [comment]
I asked for help at [reddit](https://www.reddit.com/r/jellyfin/comments/iuzs03/help_for_emby_integration/), will hopefully get some response.

**Comment by iwalton3** [comment]
This would be because the Jellyfin serializer started returning null values instead of not including the key in the response. It caused some problems for me too in jellyfin-mpv-shim.

[This code](https://github.com/mezz64/pyEmby/blob/master/pyemby/server.py#L340-L345) would have to be updated to deal with a null value for `device['NowPlayingItem']` in addition to the key not being present.

It was changed all over, so more changes for where keys historically weren't present now need to also deal with null values. I've gotten really defensive about null values coming back from Jellyfin accordingly.

**Comment by mcarlton00** [comment]
iwalton's correct.  What's happening is that some of the responses from the server are coming back as `None`.  As an example, here's the device profile I'm getting from Home Assistant.
```
{'AdditionalUsers': [],
 'ApplicationVersion': '1.6',
 'Capabilities': {'AppStoreUrl': None,
                  'DeviceProfile': None,
                  'IconUrl': None,
                  'MessageCallbackUrl': None,
                  'PlayableMediaTypes': [],
                  'SupportedCommands': [],
                  'SupportsContentUploading': False,
                  'SupportsMediaControl': False,
                  'SupportsPersistentIdentifier': True,
                  'SupportsSync': False},
 'Client': 'Home-Assistant',
 'DeviceId': '229044588395818',
 'DeviceName': 'HomeAssistant',
 'DeviceType': None,
 'FullNowPlayingItem': None,
 'HasCustomDeviceName': False,
 'Id': 'b8a8f09816c76aa04e04dbd3151f4cff',
 'IsActive': True,
 'LastActivityDate': '2020-09-20T16:04:15.3467043Z',
 'LastPlaybackCheckIn': '0001-01-01T00:00:00',
 'NowPlayingItem': None,
 'NowPlayingQueue': None,
 'NowViewingItem': None,
 'PlayState': {'AudioStreamIndex': None,
               'CanSeek': False,
               'IsMuted': False,
               'IsPaused': False,
               'MediaSourceId': None,
               'PlayMethod': None,
               'PositionTicks': None,
               'RepeatMode': 'RepeatNone',
               'SubtitleStreamIndex': None,
               'VolumeLevel': None},
 'PlayableMediaTypes': [],
 'PlaylistItemId': None,
 'RemoteEndPoint': '::ffff:192.168.0.148',
 'ServerId': '0e23a5ed08c84a159ea7d7aea7ff5e67',
 'SupportedCommands': [],
 'SupportsMediaControl': False,
 'SupportsRemoteControl': False,
 'TranscodingInfo': None,
 'UserId': '00000000-0000-0000-0000-000000000000',
 'UserName': None,
 'UserPrimaryImageTag': None}
```

Relatively easy fix, but then there's several other places in the codebase that are doing similar things where it assumes if the key exists, it will be a dict.  For example: https://github.com/mezz64/pyEmby/blob/6bb621e4e25bf1b9b0aba2c38b588e68f8816226/pyemby/server.py#L409 and https://github.com/mezz64/pyEmby/blob/6bb621e4e25bf1b9b0aba2c38b588e68f8816226/pyemby/device.py#L124-L125

I'm working through and trying to find each of them right now, should have a PR up in a bit.

**Comment by mcarlton00** [comment]
Further update: In it's current state basically every function in `device.py` that involves the `NowPlayingItem` needs refactored.  eg:
```python
@property
def media_id(self):
    """ Return title currently playing."""
    try:
        return self.session['NowPlayingItem']['Id']
    except KeyError:
        return None
```
would need to become something along the lines of
```python
@property
def media_id(self):
    """ Return title currently playing."""
    if self.session['NowPlayingItem']:
        return self.session['NowPlayingItem']['Id']
    else:
        return None
```

Obviously this would be a lot of changes in that file that may not be entirely wanted.  An alternative method would be something that we implemented in our Kodi addon that solves the problem by simply removing all keys with values of `None`.  https://github.com/jellyfin/jellyfin-kodi/blob/master/jellyfin_kodi/jellyfin/utils.py

@mezz64 let me know which direction you'd rather go with it.

**Comment by mezz64** [comment]
@mcarlton00 I'd prefer the remove None valued keys approach.  Seems much more elegant than checking everywhere.
